/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_scripts/check_account.ts" instead.
 */

#include <check.h>

#line 1 "test_scripts/check_account.ts"

#define CITS3007_PERMISSIVE

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdbool.h>
#include <arpa/inet.h>


#include "../src/account.h"
#include "../src/banned.h"
// Build command = gcc -std=c11 -Wall -Wextra -Wpedantic -Werror -o check_account test_scripts/check_account.c src/account.c src/stubs.c -lcheck -pthread -lm -lrt -lsubunit -lsodium
// Run command = ./test_scripts/check_account
#define ARR_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))



START_TEST(test_account_create_works)
{
#line 24

  const char* userid = "someuser";
  const char* email = "foo@bar.com";
  const char* plaintext_password = "Str0ng!Pass1";
  const char* birthdate = "1900-01-01";

  account_t *res = account_create(userid, plaintext_password,
                        email, birthdate
                        );

  // actual, expected
  ck_assert_str_eq(res->userid, userid);
  ck_assert_str_eq(res->email, email);
  // copy of hash
  char copy_of_hash[HASH_LENGTH + 1 ] = { 0 };
  memcpy(copy_of_hash, res->password_hash, HASH_LENGTH);
  // TODO: only if string is printable

  // password hash is NOT the same as password
  ck_assert_str_ne(copy_of_hash, plaintext_password);


}
END_TEST

START_TEST(test_account_update_password_neq_plaintext)
{
#line 49

  account_t acc = { 0 };

  const char* plaintext_password = "Str0ng!Pass1";

  bool res = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

  char copy_of_hash[HASH_LENGTH + 1 ] = { 0 };
  memcpy(copy_of_hash, acc.password_hash, HASH_LENGTH);
  // TODO: only if string is printable

  // password hash is NOT the same as password
  ck_assert_str_ne(copy_of_hash, plaintext_password);



}
END_TEST

START_TEST(test_account_validate_password_ok)
{
#line 68

  account_t acc = { 0 };

  const char* plaintext_password = "Str0ng!Pass1";

  bool res = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

  res = account_validate_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

// vim: syntax=c :
}
END_TEST

START_TEST(test_account_update_account_old_password_neq_hash)
{
#line 83

  account_t acc = { 0 };

  const char* plaintext_password = "Str0ng!Pass1";

  // Now update and extract the initial password hash for the first update:
  bool update1 = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(update1, 1);

  char copy_of_hash1[HASH_LENGTH + 1 ] = { 0 };

  memcpy(copy_of_hash1, acc.password_hash, HASH_LENGTH);

  // Now update the password again but with the same plaintext password, then assert that the hash is different:
  bool update2 = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(update2, 1);

  char copy_of_hash2[HASH_LENGTH + 1 ] = { 0 };

  memcpy(copy_of_hash2, acc.password_hash, HASH_LENGTH);

  // Check that the two hashes are different
  ck_assert_str_ne(copy_of_hash1, copy_of_hash2);

}
END_TEST
START_TEST(test_account_create_null_args)
{
#line 111
  ck_assert_ptr_eq(account_create(NULL,"Pwd1!","a@b.com","2000-01-01"), NULL);
  ck_assert_ptr_eq(account_create("u",NULL,"a@b.com","2000-01-01"), NULL);
  ck_assert_ptr_eq(account_create("u","Pwd1!",NULL,"2000-01-01"), NULL);
  ck_assert_ptr_eq(account_create("u","Pwd1!","a@b.com",NULL), NULL);

}
END_TEST

START_TEST(test_account_set_email_happy)
{
#line 117
  account_t *a=account_create("u","Strong1!","old@e.com","2000-01-01");
  ck_assert_ptr_ne(a,NULL);
  account_set_email(a,"new@e.com");
  ck_assert_str_eq(a->email,"new@e.com");
  account_free(a);

}
END_TEST

START_TEST(test_account_set_email_invalid)
{
#line 124
  account_t *a2=account_create("u","Strong1!","good@e.com","2000-01-01");
  const char *prev=a2->email;
  account_set_email(a2,"bad-email");
  ck_assert_str_eq(a2->email,prev);
  account_free(a2);

}
END_TEST

START_TEST(test_account_ban_and_expire)
{
#line 131
  account_t acc={0};
  ck_assert_int_eq(account_is_banned(&acc), false);
  account_set_unban_time(&acc, 1);
  ck_assert_int_eq(account_is_banned(&acc), true);
  account_set_unban_time(&acc, 0);
  ck_assert_int_eq(account_is_banned(&acc), false);

  ck_assert_int_eq(account_is_expired(&acc), false);
  account_set_expiration_time(&acc,1);
  ck_assert_int_eq(account_is_expired(&acc), false);
  acc.expiration_time = time(NULL)-1;
  ck_assert_int_eq(account_is_expired(&acc), true);

}
END_TEST

START_TEST(test_account_record_login)
{
#line 145
  account_t accL={0};
  accL.login_fail_count=5;
  account_record_login_success(&accL,INADDR_LOOPBACK);
  ck_assert_int_eq(accL.login_fail_count,0);
  ck_assert(accL.last_login_time>0);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("account_suite");
    TCase *tc1_1 = tcase_create("account_create_test_case");
    TCase *tc1_2 = tcase_create("account_update_password_test_case");
    TCase *tc1_3 = tcase_create("api_misc");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_account_create_works);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, test_account_update_password_neq_plaintext);
    tcase_add_test(tc1_2, test_account_validate_password_ok);
    tcase_add_test(tc1_2, test_account_update_account_old_password_neq_hash);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, test_account_create_null_args);
    tcase_add_test(tc1_3, test_account_set_email_happy);
    tcase_add_test(tc1_3, test_account_set_email_invalid);
    tcase_add_test(tc1_3, test_account_ban_and_expire);
    tcase_add_test(tc1_3, test_account_record_login);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
