/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "src/check_account.ts" instead.
 */

#include <check.h>

#line 1 "src/check_account.ts"

#define CITS3007_PERMISSIVE

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdbool.h>

#include "account.h"
#include "banned.h"

#define ARR_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))



START_TEST(test_account_create_works)
{
#line 20

  const char* userid = "someuser";
  const char* email = "foo@bar.com";
  const char* plaintext_password = "password123";
  const char* birthdate = "1900-01-01";

  account_t *res = account_create(userid, plaintext_password,
                        email, birthdate
                        );

  // actual, expected
  ck_assert_str_eq(res->userid, userid);
  ck_assert_str_eq(res->email, email);
  // copy of hash
  char copy_of_hash[HASH_LENGTH + 1 ] = { 0 };
  memcpy(copy_of_hash, res->password_hash, HASH_LENGTH);
  // TODO: only if string is printable

  // password hash is NOT the same as password
  ck_assert_str_ne(copy_of_hash, plaintext_password);


}
END_TEST

START_TEST(test_account_update_password_neq_plaintext)
{
#line 45

  account_t acc = { 0 };

  const char* plaintext_password = "password123";

  bool res = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

  char copy_of_hash[HASH_LENGTH + 1 ] = { 0 };
  memcpy(copy_of_hash, acc.password_hash, HASH_LENGTH);
  // TODO: only if string is printable

  // password hash is NOT the same as password
  ck_assert_str_ne(copy_of_hash, plaintext_password);



}
END_TEST

START_TEST(test_account_validate_password_ok)
{
#line 64

  account_t acc = { 0 };

  const char* plaintext_password = "password123";

  bool res = account_update_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

  res = account_validate_password(&acc, plaintext_password);

  ck_assert_int_eq(res, 1);

// vim: syntax=c :
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("account_suite");
    TCase *tc1_1 = tcase_create("account_create_test_case");
    TCase *tc1_2 = tcase_create("account_update_password_test_case");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_account_create_works);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, test_account_update_password_neq_plaintext);
    tcase_add_test(tc1_2, test_account_validate_password_ok);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
